# Generated by Django 2.2.10 on 2020-06-16 14:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chellenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chellengeName', models.CharField(max_length=50)),
                ('chellengeDesc', models.TextField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'Chellenge',
            },
        ),
        migrations.CreateModel(
            name='testMOdel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message Field')),
            ],
            options={
                'db_table': 'Test_MOdel',
            },
        ),
        migrations.CreateModel(
            name='TopicList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topic', models.CharField(max_length=50)),
                ('TopicDesc', models.TextField(blank=True, max_length=1000, null=True)),
                ('voteCount', models.IntegerField(blank=True, default=0)),
                ('Chellenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmat.Chellenge')),
            ],
            options={
                'db_table': 'TopicList',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='janamat/ProfileImage')),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('dob', models.DateTimeField(auto_now=True)),
                ('usr_type', models.IntegerField(choices=[(1, 'Admin'), (2, 'User')], default=2)),
            ],
            options={
                'db_table': 'UserProfile',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_comment', models.DateTimeField(default=datetime.datetime.today)),
                ('message', models.TextField(verbose_name='Message Field')),
                ('chellenge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmat.Chellenge')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Comment_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Comment',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_votted', models.BooleanField(default=False)),
                ('Chellenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmat.Chellenge')),
                ('Topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmat.TopicList')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Vote',
                'unique_together': {('Chellenge', 'User')},
            },
        ),
    ]
