# Generated by Django 2.2.10 on 2020-07-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chellenge',
            name='chellengeDesc',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='topiclist',
            name='TopicDesc',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
