# Generated by Django 2.2.10 on 2020-07-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='sno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
