# Generated by Django 2.2.10 on 2020-07-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='janamat/ProfileImage/pi.jpg', null=True, upload_to='janamat/ProfileImage'),
        ),
    ]
