# Generated by Django 2.2.10 on 2020-07-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmat', '0002_auto_20200703_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='janamat/ProfileImage'),
        ),
    ]
