# Generated by Django 2.2.10 on 2020-07-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmat', '0002_auto_20200704_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('message', models.TextField(blank=True, max_length=1000)),
            ],
            options={
                'db_table': 'Contact',
            },
        ),
    ]
