# Generated by Django 2.2.10 on 2020-07-04 18:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jmat', '0003_contact_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
