# Generated by Django 2.2.10 on 2020-07-04 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jmat', '0004_contact_us_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact_us',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
    ]
